// ═══════════════════════════════════════════
// resident.js — Resident entity (agent-like)
// This is the hook point for future AI content
// ═══════════════════════════════════════════

const Resident = {
    /**
     * Create a resident
     * @param {number} idNum - numeric ID
     * @param {string} floorEntityId - entity ID of their residential floor
     * @param {object} overrides - custom properties
     * @returns {object} resident
     */
    create(idNum, floorEntityId, overrides = {}) {
        const base = {
            id: `resident_${idNum}`,
            floorEntityId,

            // Identity (AI flavor layer hooks here)
            name: null,        // "Marla Venn" — generated by AI
            title: null,       // "Synthetic Archivist"
            bio: null,         // longer description

            // State
            mood: 'neutral',   // 'happy' | 'neutral' | 'unhappy'
            currentLocation: 'home', // 'home' | 'transit' | 'work' | 'leisure'

            // Needs (for future simulation depth)
            needs: {
                comfort: 0.7,
                social: 0.5,
                entertainment: 0.6,
            },

            // Schedule (future day/night cycle)
            schedule: null,

            // Stats
            movedIn: Date.now(),
            complaints: 0,
        };

        Object.assign(base, overrides);
        return base;
    },

    /**
     * Generate a placeholder name (until AI takes over)
     */
    generatePlaceholderName() {
        const firstNames = [
            'Alex', 'Jordan', 'Sam', 'Casey', 'Morgan',
            'Riley', 'Taylor', 'Quinn', 'Avery', 'Blake',
        ];
        const lastNames = [
            'Chen', 'Patel', 'Kim', 'Osei', 'Novak',
            'Santos', 'Mueller', 'Anders', 'Park', 'Silva',
        ];
        const fn = firstNames[Math.floor(Math.random() * firstNames.length)];
        const ln = lastNames[Math.floor(Math.random() * lastNames.length)];
        return `${fn} ${ln}`;
    },
};
window.Resident = Resident;
